-- 코드를 작성해주세요
SELECT 
    ID, 
    CASE
        WHEN (S <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.25) THEN 'CRITICAL'
        WHEN (S <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.50) THEN 'HIGH'
        WHEN (S <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.75) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
(SELECT
    ID,
    RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS S
    , SIZE_OF_COLONY
FROM 
    ECOLI_DATA) AS R
ORDER BY ID

