-- 코드를 작성해주세요
SELECT 
    Y.YEAR AS YEAR, Y.MAXSIZE - X.SIZE_OF_COLONY AS YEAR_DEV, X.ID AS ID
FROM ECOLI_DATA AS X
JOIN
(
    SELECT   MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS Y
    ON 
    Y.YEAR = YEAR(X.DIFFERENTIATION_DATE) 
ORDER BY 
    YEAR ASC, YEAR_DEV ASC
    
    