-- 코드를 작성해주세요
SELECT X.ID, Y.FISH_NAME, Y.LENGTH
FROM FISH_INFO AS X
JOIN
(
SELECT A.FISH_NAME AS FISH_NAME, B.LENGTH AS LENGTH, B.FISH_TYPE AS FISH_TYPE
FROM FISH_NAME_INFO AS A
JOIN
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM 
    FISH_INFO
GROUP BY 
    FISH_TYPE) AS B
ON 
    A.FISH_TYPE = B.FISH_TYPE) AS Y
ON
    X.FISH_TYPE = Y.FISH_TYPE
    AND 
    X.LENGTH = Y.LENGTH
ORDER BY 
    X.ID

